
import { db } from '../services/firestore.service.js';

export const usersCollection = db.collection('users');
export const organizationsCollection = db.collection('organizations');
export const academiesCollection = db.collection('academies');
export const academySettingsCollection = db.collection('academySettings');
export const conversationsCollection = db.collection('conversations');
export const triggerPhrasesCollection = db.collection('triggerPhrases');
export const preapprovedUsersCollection = db.collection('preapprovedUsers');
export const questionnairesCollection = db.collection('questionnaires');
export const userQuestionnaireResultsCollection = db.collection('userQuestionnaireResults');
export const coursesCollection = db.collection('courses');
export const userCourseProgressCollection = db.collection('userCourseProgress');
export const tokenUsageCollection = db.collection('tokenUsage');
export const chatPersonasCollection = db.collection('chatPersonas');
export const plansCollection = db.collection('plans');
export const systemSettingsCollection = db.collection('systemSettings');
export const userAccessStatusCollection = db.collection('userAccessStatus');
export const membershipsCollection = db.collection('memberships');
export const personalInsightsCollection = db.collection('personalInsights');
export const academyBillingCyclesCollection = db.collection('academyBillingCycles');
export const transactionsCollection = db.collection('transactions');
export const pendingCheckoutsCollection = db.collection('pendingCheckouts');
export const paymentSessionsCollection = db.collection('paymentSessions');
export const paymentInitiationSessionsCollection = db.collection('paymentInitiationSessions');
export const newsletterCampaignsCollection = db.collection('newsletterCampaigns');
export const newsletterEditionsCollection = db.collection('newsletterEditions');
export const unsubscriptionsCollection = db.collection('unsubscriptions');
export const triggerEnrollmentsCollection = db.collection('triggerEnrollments');
export const emailTemplatesCollection = db.collection('emailTemplates');
export const auditLogsCollection = db.collection('auditLogs');
