export interface EmojiEntry {
  emoji: string;
  keywords: string[];
  category: string;
}

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys & Faces
  { emoji: '😀', keywords: ['grin','grinning','happy','smile','smiley','joy'], category: 'Smileys' },
  { emoji: '😃', keywords: ['smiley','happy','smile','open mouth'], category: 'Smileys' },
  { emoji: '😄', keywords: ['smile','happy','joy','grin'], category: 'Smileys' },
  { emoji: '😁', keywords: ['beaming','grin','happy'], category: 'Smileys' },
  { emoji: '😆', keywords: ['laughing','lol','haha','happy'], category: 'Smileys' },
  { emoji: '😅', keywords: ['sweat','nervous','laugh'], category: 'Smileys' },
  { emoji: '🤣', keywords: ['rofl','rolling','laugh','lol','funny'], category: 'Smileys' },
  { emoji: '😂', keywords: ['joy','cry','laugh','tears','funny','lol'], category: 'Smileys' },
  { emoji: '🙂', keywords: ['smile','slight','happy'], category: 'Smileys' },
  { emoji: '🙃', keywords: ['upside down','sarcasm','irony'], category: 'Smileys' },
  { emoji: '😉', keywords: ['wink','flirt'], category: 'Smileys' },
  { emoji: '😊', keywords: ['blush','smile','happy','shy'], category: 'Smileys' },
  { emoji: '😇', keywords: ['halo','angel','innocent','good'], category: 'Smileys' },
  { emoji: '🥰', keywords: ['love','hearts','adore','crush'], category: 'Smileys' },
  { emoji: '😍', keywords: ['heart eyes','love','adore'], category: 'Smileys' },
  { emoji: '🤩', keywords: ['star struck','amazing','wow','celebrity'], category: 'Smileys' },
  { emoji: '😘', keywords: ['kiss','love','heart','blowing'], category: 'Smileys' },
  { emoji: '😎', keywords: ['cool','sunglasses','confident'], category: 'Smileys' },
  { emoji: '🤓', keywords: ['nerd','glasses','smart','geek'], category: 'Smileys' },
  { emoji: '🧐', keywords: ['monocle','curious','inspect','fancy'], category: 'Smileys' },
  { emoji: '😏', keywords: ['smirk','smug','sly'], category: 'Smileys' },
  { emoji: '😒', keywords: ['unamused','bored','meh'], category: 'Smileys' },
  { emoji: '😞', keywords: ['disappointed','sad','let down'], category: 'Smileys' },
  { emoji: '😔', keywords: ['pensive','sad','thoughtful'], category: 'Smileys' },
  { emoji: '😟', keywords: ['worried','concerned','anxious'], category: 'Smileys' },
  { emoji: '😕', keywords: ['confused','unsure'], category: 'Smileys' },
  { emoji: '🙁', keywords: ['sad','frowning','unhappy'], category: 'Smileys' },
  { emoji: '😣', keywords: ['persevering','struggle','pain'], category: 'Smileys' },
  { emoji: '😖', keywords: ['confounded','frustrated'], category: 'Smileys' },
  { emoji: '😫', keywords: ['tired','weary','exhausted'], category: 'Smileys' },
  { emoji: '😩', keywords: ['weary','tired','exhausted'], category: 'Smileys' },
  { emoji: '🥺', keywords: ['pleading','puppy eyes','beg'], category: 'Smileys' },
  { emoji: '😢', keywords: ['cry','sad','tear'], category: 'Smileys' },
  { emoji: '😭', keywords: ['sob','cry','loud','tears'], category: 'Smileys' },
  { emoji: '😤', keywords: ['triumph','huff','frustrated'], category: 'Smileys' },
  { emoji: '😠', keywords: ['angry','mad','furious'], category: 'Smileys' },
  { emoji: '😡', keywords: ['rage','angry','red face','furious'], category: 'Smileys' },
  { emoji: '🤬', keywords: ['swearing','cursing','angry'], category: 'Smileys' },
  { emoji: '🤯', keywords: ['exploding head','mind blown','shock'], category: 'Smileys' },
  { emoji: '😳', keywords: ['flushed','embarrassed','shocked'], category: 'Smileys' },
  { emoji: '🥵', keywords: ['hot','overheated','sweating'], category: 'Smileys' },
  { emoji: '🥶', keywords: ['cold','freezing','frozen'], category: 'Smileys' },
  { emoji: '😱', keywords: ['scream','scared','horror','fear'], category: 'Smileys' },
  { emoji: '😨', keywords: ['fearful','scared'], category: 'Smileys' },
  { emoji: '😰', keywords: ['anxious sweat','nervous'], category: 'Smileys' },
  { emoji: '😥', keywords: ['sad','disappointed','relieved'], category: 'Smileys' },
  { emoji: '😓', keywords: ['downcast','sweat'], category: 'Smileys' },
  { emoji: '🤗', keywords: ['hugging','hug','warm'], category: 'Smileys' },
  { emoji: '🤔', keywords: ['thinking','hmm','curious','ponder'], category: 'Smileys' },
  { emoji: '🫡', keywords: ['salute','respect','military'], category: 'Smileys' },
  { emoji: '🤭', keywords: ['shush','giggle','secret'], category: 'Smileys' },
  { emoji: '🤫', keywords: ['shush','quiet','secret','silent'], category: 'Smileys' },
  { emoji: '🫢', keywords: ['gasp','shock','surprise','mouth'], category: 'Smileys' },
  { emoji: '🤐', keywords: ['zipper mouth','silent','shush'], category: 'Smileys' },
  { emoji: '🤨', keywords: ['raised eyebrow','skeptical'], category: 'Smileys' },
  { emoji: '😐', keywords: ['neutral','blank','meh'], category: 'Smileys' },
  { emoji: '😑', keywords: ['expressionless','blank'], category: 'Smileys' },
  { emoji: '😬', keywords: ['grimace','awkward'], category: 'Smileys' },
  { emoji: '🙄', keywords: ['eye roll','whatever','bored'], category: 'Smileys' },
  { emoji: '😯', keywords: ['hushed','surprised'], category: 'Smileys' },
  { emoji: '😦', keywords: ['frowning','surprised'], category: 'Smileys' },
  { emoji: '😧', keywords: ['anguished','shocked'], category: 'Smileys' },
  { emoji: '😮', keywords: ['open mouth','wow','surprised'], category: 'Smileys' },
  { emoji: '🤐', keywords: ['zipper','silent','shush'], category: 'Smileys' },
  { emoji: '😴', keywords: ['sleep','tired','zzz'], category: 'Smileys' },
  { emoji: '🤤', keywords: ['drool','hungry','tasty'], category: 'Smileys' },
  { emoji: '😪', keywords: ['sleepy','tired'], category: 'Smileys' },
  { emoji: '😵', keywords: ['dizzy','confused','knocked out'], category: 'Smileys' },
  { emoji: '🤕', keywords: ['sick','injury','bandage','hurt'], category: 'Smileys' },
  { emoji: '🤒', keywords: ['sick','temperature','ill'], category: 'Smileys' },
  { emoji: '🤢', keywords: ['nausea','sick','green'], category: 'Smileys' },
  { emoji: '🤮', keywords: ['vomit','sick','puke'], category: 'Smileys' },
  { emoji: '🤧', keywords: ['sneezing','sick','cold'], category: 'Smileys' },
  { emoji: '😷', keywords: ['mask','sick','medical'], category: 'Smileys' },
  { emoji: '🥴', keywords: ['woozy','drunk','dizzy'], category: 'Smileys' },
  { emoji: '🤠', keywords: ['cowboy','hat','western'], category: 'Smileys' },
  { emoji: '🥳', keywords: ['party','celebrate','hat','birthday'], category: 'Smileys' },
  { emoji: '🥸', keywords: ['disguise','glasses','nose','spy'], category: 'Smileys' },
  { emoji: '👿', keywords: ['devil','evil','angry'], category: 'Smileys' },
  { emoji: '😈', keywords: ['devil','evil','smile'], category: 'Smileys' },
  { emoji: '👻', keywords: ['ghost','halloween','boo','spooky'], category: 'Smileys' },
  { emoji: '💀', keywords: ['skull','death','danger','skeleton'], category: 'Smileys' },
  { emoji: '☠', keywords: ['skull crossbones','danger','pirate','poison'], category: 'Smileys' },
  { emoji: '💩', keywords: ['poop','poo','funny'], category: 'Smileys' },
  { emoji: '🤡', keywords: ['clown','circus','funny'], category: 'Smileys' },
  { emoji: '🎃', keywords: ['halloween','pumpkin','jack','lantern'], category: 'Smileys' },
  // People & Hands
  { emoji: '👋', keywords: ['wave','hello','bye','hand'], category: 'People' },
  { emoji: '👍', keywords: ['thumbs up','like','approve','good','yes'], category: 'People' },
  { emoji: '👎', keywords: ['thumbs down','dislike','no','bad'], category: 'People' },
  { emoji: '👌', keywords: ['ok','perfect','fine','good'], category: 'People' },
  { emoji: '✌', keywords: ['peace','victory','two','fingers'], category: 'People' },
  { emoji: '🤞', keywords: ['crossed fingers','luck','hope'], category: 'People' },
  { emoji: '🤙', keywords: ['call me','hang loose','phone','surf'], category: 'People' },
  { emoji: '💪', keywords: ['muscle','strong','flex','power','strength'], category: 'People' },
  { emoji: '🙏', keywords: ['pray','please','thanks','hands','namaste'], category: 'People' },
  { emoji: '👏', keywords: ['clap','applause','praise','bravo'], category: 'People' },
  { emoji: '🙌', keywords: ['raised hands','praise','celebrate','hooray'], category: 'People' },
  { emoji: '🤝', keywords: ['handshake','deal','agree','partnership'], category: 'People' },
  { emoji: '✊', keywords: ['fist','raised','power','protest','fight'], category: 'People' },
  { emoji: '👊', keywords: ['punch','fist','fight'], category: 'People' },
  { emoji: '🤜', keywords: ['fist bump','right','punch'], category: 'People' },
  { emoji: '🤛', keywords: ['fist bump','left'], category: 'People' },
  { emoji: '☝', keywords: ['point up','one','finger','index'], category: 'People' },
  { emoji: '👆', keywords: ['point up','above','backhand'], category: 'People' },
  { emoji: '👇', keywords: ['point down','below'], category: 'People' },
  { emoji: '👈', keywords: ['point left','backhand'], category: 'People' },
  { emoji: '👉', keywords: ['point right','backhand'], category: 'People' },
  { emoji: '🖕', keywords: ['middle finger','rude'], category: 'People' },
  { emoji: '🤌', keywords: ['pinch','italian','fingers'], category: 'People' },
  { emoji: '🫶', keywords: ['heart hands','love','care'], category: 'People' },
  { emoji: '🧠', keywords: ['brain','smart','think','mind','intelligence'], category: 'People' },
  { emoji: '👁', keywords: ['eye','see','watch'], category: 'People' },
  { emoji: '👀', keywords: ['eyes','see','look','watch'], category: 'People' },
  { emoji: '👂', keywords: ['ear','listen','hear'], category: 'People' },
  { emoji: '👃', keywords: ['nose','smell'], category: 'People' },
  { emoji: '💋', keywords: ['kiss','lips','love'], category: 'People' },
  { emoji: '💅', keywords: ['nails','manicure','polish'], category: 'People' },
  { emoji: '🦷', keywords: ['tooth','teeth','dental'], category: 'People' },
  { emoji: '🦴', keywords: ['bone','skeleton'], category: 'People' },
  // Animals
  { emoji: '🐶', keywords: ['dog','puppy','pet','animal'], category: 'Animals' },
  { emoji: '🐱', keywords: ['cat','kitten','pet','meow'], category: 'Animals' },
  { emoji: '🐭', keywords: ['mouse','rodent'], category: 'Animals' },
  { emoji: '🐹', keywords: ['hamster','rodent'], category: 'Animals' },
  { emoji: '🐰', keywords: ['rabbit','bunny','easter'], category: 'Animals' },
  { emoji: '🦊', keywords: ['fox','animal'], category: 'Animals' },
  { emoji: '🐻', keywords: ['bear','animal'], category: 'Animals' },
  { emoji: '🐼', keywords: ['panda','bear','china'], category: 'Animals' },
  { emoji: '🐨', keywords: ['koala','australia'], category: 'Animals' },
  { emoji: '🐯', keywords: ['tiger','wild','stripe'], category: 'Animals' },
  { emoji: '🦁', keywords: ['lion','wild','king','roar'], category: 'Animals' },
  { emoji: '🐮', keywords: ['cow','moo','farm','bull'], category: 'Animals' },
  { emoji: '🐷', keywords: ['pig','pork','oink','farm'], category: 'Animals' },
  { emoji: '🐸', keywords: ['frog','green','croak'], category: 'Animals' },
  { emoji: '🐵', keywords: ['monkey','ape','primate'], category: 'Animals' },
  { emoji: '🐒', keywords: ['monkey','primate'], category: 'Animals' },
  { emoji: '🦆', keywords: ['duck','bird','quack'], category: 'Animals' },
  { emoji: '🐧', keywords: ['penguin','bird','cold'], category: 'Animals' },
  { emoji: '🐦', keywords: ['bird','tweet','fly'], category: 'Animals' },
  { emoji: '🦅', keywords: ['eagle','bird','raptor','fly'], category: 'Animals' },
  { emoji: '🦉', keywords: ['owl','bird','wise','night'], category: 'Animals' },
  { emoji: '🦇', keywords: ['bat','halloween','night','vampire'], category: 'Animals' },
  { emoji: '🐝', keywords: ['bee','honey','insect','sting'], category: 'Animals' },
  { emoji: '🐛', keywords: ['bug','caterpillar','worm','insect'], category: 'Animals' },
  { emoji: '🦋', keywords: ['butterfly','insect','beautiful'], category: 'Animals' },
  { emoji: '🐌', keywords: ['snail','slow'], category: 'Animals' },
  { emoji: '🐞', keywords: ['ladybug','ladybird','insect'], category: 'Animals' },
  { emoji: '🐜', keywords: ['ant','insect'], category: 'Animals' },
  { emoji: '🦟', keywords: ['mosquito','insect','bite'], category: 'Animals' },
  { emoji: '🦗', keywords: ['cricket','insect'], category: 'Animals' },
  { emoji: '🕷', keywords: ['spider','arachnid','web','creepy','scary'], category: 'Animals' },
  { emoji: '🕸', keywords: ['spider web','cobweb','trap'], category: 'Animals' },
  { emoji: '🦂', keywords: ['scorpion','arachnid','sting','desert'], category: 'Animals' },
  { emoji: '🐢', keywords: ['turtle','tortoise','slow','green'], category: 'Animals' },
  { emoji: '🐍', keywords: ['snake','reptile','slither','venom'], category: 'Animals' },
  { emoji: '🦎', keywords: ['lizard','reptile'], category: 'Animals' },
  { emoji: '🦖', keywords: ['t-rex','dinosaur','trex','jurassic'], category: 'Animals' },
  { emoji: '🦕', keywords: ['sauropod','dinosaur','long neck','brachiosaurus'], category: 'Animals' },
  { emoji: '🐙', keywords: ['octopus','sea','tentacle'], category: 'Animals' },
  { emoji: '🦑', keywords: ['squid','sea','tentacle'], category: 'Animals' },
  { emoji: '🦐', keywords: ['shrimp','seafood'], category: 'Animals' },
  { emoji: '🦀', keywords: ['crab','seafood','sea'], category: 'Animals' },
  { emoji: '🐡', keywords: ['blowfish','puffer','fish','sea'], category: 'Animals' },
  { emoji: '🐠', keywords: ['tropical fish','clownfish','nemo','sea'], category: 'Animals' },
  { emoji: '🐟', keywords: ['fish','sea','ocean'], category: 'Animals' },
  { emoji: '🐬', keywords: ['dolphin','sea','ocean'], category: 'Animals' },
  { emoji: '🐳', keywords: ['whale','sea','ocean','spout'], category: 'Animals' },
  { emoji: '🦈', keywords: ['shark','fish','danger','ocean','jaws'], category: 'Animals' },
  { emoji: '🐊', keywords: ['crocodile','alligator','reptile'], category: 'Animals' },
  { emoji: '🐅', keywords: ['tiger','stripe','wild'], category: 'Animals' },
  { emoji: '🐆', keywords: ['leopard','spot','wild','cheetah'], category: 'Animals' },
  { emoji: '🦓', keywords: ['zebra','stripe','africa'], category: 'Animals' },
  { emoji: '🐘', keywords: ['elephant','trunk','big'], category: 'Animals' },
  { emoji: '🦒', keywords: ['giraffe','tall','neck','africa'], category: 'Animals' },
  { emoji: '🦘', keywords: ['kangaroo','australia','jump'], category: 'Animals' },
  { emoji: '🐕', keywords: ['dog','pet','animal'], category: 'Animals' },
  { emoji: '🐩', keywords: ['poodle','dog','pet'], category: 'Animals' },
  { emoji: '🐈', keywords: ['cat','pet'], category: 'Animals' },
  { emoji: '🐓', keywords: ['rooster','chicken','farm'], category: 'Animals' },
  { emoji: '🦃', keywords: ['turkey','thanksgiving','bird'], category: 'Animals' },
  { emoji: '🐇', keywords: ['rabbit','bunny','hare'], category: 'Animals' },
  { emoji: '🦔', keywords: ['hedgehog','spiky'], category: 'Animals' },
  { emoji: '🐿', keywords: ['chipmunk','squirrel','nut'], category: 'Animals' },
  { emoji: '🦦', keywords: ['otter','sea','play'], category: 'Animals' },
  { emoji: '🦥', keywords: ['sloth','slow','lazy'], category: 'Animals' },
  // Food & Drink
  { emoji: '🍎', keywords: ['apple','red','fruit'], category: 'Food' },
  { emoji: '🍊', keywords: ['orange','tangerine','fruit'], category: 'Food' },
  { emoji: '🍋', keywords: ['lemon','citrus','sour','fruit'], category: 'Food' },
  { emoji: '🍇', keywords: ['grapes','fruit','wine'], category: 'Food' },
  { emoji: '🍓', keywords: ['strawberry','red','fruit'], category: 'Food' },
  { emoji: '🫐', keywords: ['blueberry','fruit'], category: 'Food' },
  { emoji: '🍒', keywords: ['cherry','red','fruit'], category: 'Food' },
  { emoji: '🍑', keywords: ['peach','fruit'], category: 'Food' },
  { emoji: '🍍', keywords: ['pineapple','tropical','fruit'], category: 'Food' },
  { emoji: '🥭', keywords: ['mango','tropical','fruit'], category: 'Food' },
  { emoji: '🥥', keywords: ['coconut','tropical'], category: 'Food' },
  { emoji: '🥝', keywords: ['kiwi','fruit','green'], category: 'Food' },
  { emoji: '🍅', keywords: ['tomato','red','vegetable'], category: 'Food' },
  { emoji: '🍆', keywords: ['eggplant','aubergine','purple','vegetable'], category: 'Food' },
  { emoji: '🥑', keywords: ['avocado','green','healthy'], category: 'Food' },
  { emoji: '🥦', keywords: ['broccoli','green','vegetable','healthy'], category: 'Food' },
  { emoji: '🥕', keywords: ['carrot','orange','vegetable','rabbit'], category: 'Food' },
  { emoji: '🌽', keywords: ['corn','vegetable'], category: 'Food' },
  { emoji: '🌶', keywords: ['pepper','hot','chili','spicy'], category: 'Food' },
  { emoji: '🧄', keywords: ['garlic','cooking','smell'], category: 'Food' },
  { emoji: '🧅', keywords: ['onion','cooking'], category: 'Food' },
  { emoji: '🥔', keywords: ['potato','vegetable'], category: 'Food' },
  { emoji: '🍄', keywords: ['mushroom','fungi','mario'], category: 'Food' },
  { emoji: '🌰', keywords: ['chestnut','nut','autumn'], category: 'Food' },
  { emoji: '🍞', keywords: ['bread','loaf'], category: 'Food' },
  { emoji: '🥐', keywords: ['croissant','pastry','french','breakfast'], category: 'Food' },
  { emoji: '🥨', keywords: ['pretzel','bread','twist'], category: 'Food' },
  { emoji: '🧀', keywords: ['cheese','dairy'], category: 'Food' },
  { emoji: '🥚', keywords: ['egg','breakfast'], category: 'Food' },
  { emoji: '🍳', keywords: ['frying pan','egg','cooking','breakfast'], category: 'Food' },
  { emoji: '🥞', keywords: ['pancake','breakfast','syrup'], category: 'Food' },
  { emoji: '🧇', keywords: ['waffle','breakfast'], category: 'Food' },
  { emoji: '🥓', keywords: ['bacon','breakfast','meat'], category: 'Food' },
  { emoji: '🥩', keywords: ['steak','meat','beef'], category: 'Food' },
  { emoji: '🍗', keywords: ['chicken leg','drumstick','poultry'], category: 'Food' },
  { emoji: '🍖', keywords: ['meat on bone','bone','meat'], category: 'Food' },
  { emoji: '🌭', keywords: ['hotdog','sausage','fast food'], category: 'Food' },
  { emoji: '🍔', keywords: ['burger','hamburger','fast food'], category: 'Food' },
  { emoji: '🍟', keywords: ['fries','french fries','fast food'], category: 'Food' },
  { emoji: '🍕', keywords: ['pizza','slice','italian','fast food'], category: 'Food' },
  { emoji: '🌮', keywords: ['taco','mexican','food'], category: 'Food' },
  { emoji: '🌯', keywords: ['burrito','wrap','mexican'], category: 'Food' },
  { emoji: '🥗', keywords: ['salad','green','healthy'], category: 'Food' },
  { emoji: '🍲', keywords: ['stew','pot','soup'], category: 'Food' },
  { emoji: '🍜', keywords: ['noodles','ramen','soup','asian'], category: 'Food' },
  { emoji: '🍝', keywords: ['spaghetti','pasta','italian'], category: 'Food' },
  { emoji: '🍣', keywords: ['sushi','japanese','rice','fish'], category: 'Food' },
  { emoji: '🍱', keywords: ['bento','box','japanese','lunch'], category: 'Food' },
  { emoji: '🍩', keywords: ['donut','doughnut','sweet','ring'], category: 'Food' },
  { emoji: '🍪', keywords: ['cookie','biscuit','sweet'], category: 'Food' },
  { emoji: '🎂', keywords: ['birthday cake','cake','candle','party'], category: 'Food' },
  { emoji: '🍰', keywords: ['cake','slice','shortcake','sweet'], category: 'Food' },
  { emoji: '🧁', keywords: ['cupcake','muffin','sweet'], category: 'Food' },
  { emoji: '🍫', keywords: ['chocolate','bar','sweet'], category: 'Food' },
  { emoji: '🍬', keywords: ['candy','sweet','sugar'], category: 'Food' },
  { emoji: '🍭', keywords: ['lollipop','candy','sweet'], category: 'Food' },
  { emoji: '🍦', keywords: ['ice cream','soft serve','cone'], category: 'Food' },
  { emoji: '🍨', keywords: ['ice cream','scoop','sweet'], category: 'Food' },
  { emoji: '☕', keywords: ['coffee','hot','cafe','morning'], category: 'Food' },
  { emoji: '🫖', keywords: ['teapot','tea','hot'], category: 'Food' },
  { emoji: '🍵', keywords: ['tea','green tea','hot'], category: 'Food' },
  { emoji: '🍺', keywords: ['beer','mug','pub','drink','alcohol'], category: 'Food' },
  { emoji: '🍻', keywords: ['beer','cheers','toast','drink','alcohol'], category: 'Food' },
  { emoji: '🍷', keywords: ['wine','red wine','drink','alcohol'], category: 'Food' },
  { emoji: '🍸', keywords: ['cocktail','martini','drink','alcohol'], category: 'Food' },
  { emoji: '🥂', keywords: ['champagne','toast','celebrate','drink'], category: 'Food' },
  { emoji: '🧃', keywords: ['juice','drink','box'], category: 'Food' },
  { emoji: '🧉', keywords: ['mate','drink'], category: 'Food' },
  // Travel & Places
  { emoji: '🚗', keywords: ['car','automobile','drive','vehicle'], category: 'Travel' },
  { emoji: '🚕', keywords: ['taxi','cab','car','yellow'], category: 'Travel' },
  { emoji: '🚙', keywords: ['suv','car','vehicle'], category: 'Travel' },
  { emoji: '🚌', keywords: ['bus','transit','vehicle','public transport'], category: 'Travel' },
  { emoji: '🏎', keywords: ['race car','formula','fast','speed'], category: 'Travel' },
  { emoji: '🚓', keywords: ['police car','cop','patrol'], category: 'Travel' },
  { emoji: '🚑', keywords: ['ambulance','emergency','medical','hospital'], category: 'Travel' },
  { emoji: '🚒', keywords: ['fire truck','fire engine','emergency'], category: 'Travel' },
  { emoji: '🚜', keywords: ['tractor','farm','agriculture'], category: 'Travel' },
  { emoji: '🏍', keywords: ['motorcycle','motorbike','bike'], category: 'Travel' },
  { emoji: '🚲', keywords: ['bicycle','bike','cycle'], category: 'Travel' },
  { emoji: '🛹', keywords: ['skateboard','skate'], category: 'Travel' },
  { emoji: '⛽', keywords: ['fuel','gas','petrol','station'], category: 'Travel' },
  { emoji: '🚦', keywords: ['traffic light','stop','signal'], category: 'Travel' },
  { emoji: '⚓', keywords: ['anchor','ship','boat','navy'], category: 'Travel' },
  { emoji: '⛵', keywords: ['sailboat','boat','sail','sea'], category: 'Travel' },
  { emoji: '🚤', keywords: ['speedboat','boat','fast','sea'], category: 'Travel' },
  { emoji: '🚢', keywords: ['ship','cruise','ocean','boat'], category: 'Travel' },
  { emoji: '✈', keywords: ['airplane','plane','fly','travel','flight'], category: 'Travel' },
  { emoji: '🚀', keywords: ['rocket','space','launch','nasa'], category: 'Travel' },
  { emoji: '🛸', keywords: ['ufo','alien','flying saucer','space'], category: 'Travel' },
  { emoji: '🚁', keywords: ['helicopter','fly','rotorcraft'], category: 'Travel' },
  { emoji: '🏔', keywords: ['mountain','snow','peak','alpine'], category: 'Travel' },
  { emoji: '⛰', keywords: ['mountain','peak'], category: 'Travel' },
  { emoji: '🌋', keywords: ['volcano','eruption','mountain','lava'], category: 'Travel' },
  { emoji: '🏕', keywords: ['camping','tent','outdoor'], category: 'Travel' },
  { emoji: '🏖', keywords: ['beach','sand','vacation','summer'], category: 'Travel' },
  { emoji: '🏝', keywords: ['island','tropical','desert island'], category: 'Travel' },
  { emoji: '🗼', keywords: ['eiffel tower','paris','france'], category: 'Travel' },
  { emoji: '🗽', keywords: ['statue of liberty','new york','america'], category: 'Travel' },
  { emoji: '⛩', keywords: ['shinto shrine','japan','gate'], category: 'Travel' },
  { emoji: '🏰', keywords: ['castle','medieval','palace','fortress'], category: 'Travel' },
  { emoji: '🏯', keywords: ['japanese castle','japan','fortress'], category: 'Travel' },
  { emoji: '🏠', keywords: ['house','home','building'], category: 'Travel' },
  { emoji: '🏢', keywords: ['office building','business','city'], category: 'Travel' },
  { emoji: '🏥', keywords: ['hospital','medical','health'], category: 'Travel' },
  { emoji: '🏦', keywords: ['bank','money','finance'], category: 'Travel' },
  { emoji: '🏨', keywords: ['hotel','stay','travel','lodging'], category: 'Travel' },
  { emoji: '🌅', keywords: ['sunrise','morning','dawn','sun'], category: 'Travel' },
  { emoji: '🌄', keywords: ['sunrise over mountains','dawn','morning'], category: 'Travel' },
  { emoji: '🌇', keywords: ['sunset','city','evening'], category: 'Travel' },
  { emoji: '🌆', keywords: ['cityscape','city','evening'], category: 'Travel' },
  { emoji: '🌉', keywords: ['bridge','night','city','lights'], category: 'Travel' },
  { emoji: '🗺', keywords: ['world map','atlas','geography','travel'], category: 'Travel' },
  { emoji: '🧭', keywords: ['compass','direction','navigation'], category: 'Travel' },
  // Activities & Sports
  { emoji: '⚽', keywords: ['soccer','football','ball','sport'], category: 'Activities' },
  { emoji: '🏀', keywords: ['basketball','ball','sport','nba'], category: 'Activities' },
  { emoji: '🏈', keywords: ['american football','nfl','ball','sport'], category: 'Activities' },
  { emoji: '⚾', keywords: ['baseball','ball','sport','mlb'], category: 'Activities' },
  { emoji: '🎾', keywords: ['tennis','ball','sport','racket'], category: 'Activities' },
  { emoji: '🏐', keywords: ['volleyball','ball','sport'], category: 'Activities' },
  { emoji: '🏒', keywords: ['ice hockey','puck','sport'], category: 'Activities' },
  { emoji: '🏓', keywords: ['ping pong','table tennis','paddle','sport'], category: 'Activities' },
  { emoji: '🏸', keywords: ['badminton','shuttlecock','sport','racket'], category: 'Activities' },
  { emoji: '🥊', keywords: ['boxing glove','fight','sport'], category: 'Activities' },
  { emoji: '🥋', keywords: ['martial arts','karate','judo','sport'], category: 'Activities' },
  { emoji: '⛳', keywords: ['golf','flag','sport','hole'], category: 'Activities' },
  { emoji: '🎣', keywords: ['fishing','fish','rod','hobby'], category: 'Activities' },
  { emoji: '🤿', keywords: ['diving','scuba','snorkel','swim'], category: 'Activities' },
  { emoji: '🎿', keywords: ['ski','skiing','snow','winter sport'], category: 'Activities' },
  { emoji: '⛷', keywords: ['skier','ski','snow','winter sport'], category: 'Activities' },
  { emoji: '🏂', keywords: ['snowboard','snow','winter sport'], category: 'Activities' },
  { emoji: '🏄', keywords: ['surfing','wave','beach','sport'], category: 'Activities' },
  { emoji: '🏊', keywords: ['swimming','pool','water','sport'], category: 'Activities' },
  { emoji: '🚴', keywords: ['cycling','bike','sport'], category: 'Activities' },
  { emoji: '🏋', keywords: ['weightlifting','gym','strength','sport'], category: 'Activities' },
  { emoji: '🧘', keywords: ['yoga','meditation','lotus','peace'], category: 'Activities' },
  { emoji: '🤸', keywords: ['gymnastics','cartwheel','sport'], category: 'Activities' },
  { emoji: '🏆', keywords: ['trophy','winner','award','prize','champion'], category: 'Activities' },
  { emoji: '🥇', keywords: ['gold medal','first','winner','olympic'], category: 'Activities' },
  { emoji: '🥈', keywords: ['silver medal','second','olympic'], category: 'Activities' },
  { emoji: '🥉', keywords: ['bronze medal','third','olympic'], category: 'Activities' },
  { emoji: '🏅', keywords: ['medal','award','sport'], category: 'Activities' },
  { emoji: '🎖', keywords: ['military medal','honor','award'], category: 'Activities' },
  { emoji: '🎗', keywords: ['ribbon','awareness','cause'], category: 'Activities' },
  { emoji: '🎯', keywords: ['bullseye','target','dart','aim','goal'], category: 'Activities' },
  { emoji: '🎳', keywords: ['bowling','ball','pins','sport'], category: 'Activities' },
  { emoji: '🎮', keywords: ['video game','controller','gaming','play','console'], category: 'Activities' },
  { emoji: '🎰', keywords: ['slot machine','casino','gamble','lucky'], category: 'Activities' },
  { emoji: '🧩', keywords: ['puzzle','jigsaw','piece','strategy'], category: 'Activities' },
  { emoji: '🎲', keywords: ['dice','game','random','luck','board game'], category: 'Activities' },
  { emoji: '♟', keywords: ['chess','pawn','strategy','board game'], category: 'Activities' },
  { emoji: '🎭', keywords: ['theater','drama','masks','performing arts'], category: 'Activities' },
  { emoji: '🎨', keywords: ['art','palette','paint','creative'], category: 'Activities' },
  { emoji: '🎬', keywords: ['clapper','film','movie','cinema'], category: 'Activities' },
  { emoji: '🎤', keywords: ['microphone','sing','music','karaoke'], category: 'Activities' },
  { emoji: '🎧', keywords: ['headphones','music','listen','audio'], category: 'Activities' },
  { emoji: '🎼', keywords: ['musical score','music','notes','sheet'], category: 'Activities' },
  { emoji: '🎹', keywords: ['piano','keyboard','music','instrument'], category: 'Activities' },
  { emoji: '🥁', keywords: ['drum','percussion','music','beat'], category: 'Activities' },
  { emoji: '🎷', keywords: ['saxophone','sax','jazz','music'], category: 'Activities' },
  { emoji: '🎺', keywords: ['trumpet','brass','music'], category: 'Activities' },
  { emoji: '🎸', keywords: ['guitar','electric','music','rock'], category: 'Activities' },
  { emoji: '🎻', keywords: ['violin','string','music','classical'], category: 'Activities' },
  { emoji: '🎪', keywords: ['circus','tent','carnival'], category: 'Activities' },
  // Objects & Tech
  { emoji: '📱', keywords: ['phone','mobile','smartphone','iphone','android'], category: 'Objects' },
  { emoji: '💻', keywords: ['laptop','computer','macbook','tech'], category: 'Objects' },
  { emoji: '🖥', keywords: ['desktop','computer','monitor','screen'], category: 'Objects' },
  { emoji: '⌨', keywords: ['keyboard','type','computer'], category: 'Objects' },
  { emoji: '🖱', keywords: ['mouse','computer','click'], category: 'Objects' },
  { emoji: '💾', keywords: ['floppy disk','save','storage','data'], category: 'Objects' },
  { emoji: '💿', keywords: ['cd','disc','optical','dvd'], category: 'Objects' },
  { emoji: '📀', keywords: ['dvd','disc','optical'], category: 'Objects' },
  { emoji: '🖨', keywords: ['printer','print'], category: 'Objects' },
  { emoji: '📷', keywords: ['camera','photo','picture','photograph'], category: 'Objects' },
  { emoji: '📸', keywords: ['camera flash','photo','selfie','picture'], category: 'Objects' },
  { emoji: '📹', keywords: ['video camera','film','record'], category: 'Objects' },
  { emoji: '🎥', keywords: ['movie camera','film','cinema','video'], category: 'Objects' },
  { emoji: '📺', keywords: ['television','tv','screen','watch'], category: 'Objects' },
  { emoji: '📻', keywords: ['radio','music','broadcast','antenna'], category: 'Objects' },
  { emoji: '📞', keywords: ['telephone','phone','call','landline'], category: 'Objects' },
  { emoji: '📡', keywords: ['satellite dish','antenna','signal','broadcast'], category: 'Objects' },
  { emoji: '🔋', keywords: ['battery','charge','power','energy'], category: 'Objects' },
  { emoji: '💡', keywords: ['light bulb','idea','bright','electricity'], category: 'Objects' },
  { emoji: '🔦', keywords: ['flashlight','torch','light'], category: 'Objects' },
  { emoji: '🕯', keywords: ['candle','light','flame','romantic'], category: 'Objects' },
  { emoji: '🔑', keywords: ['key','lock','security','access'], category: 'Objects' },
  { emoji: '🗝', keywords: ['old key','antique','lock'], category: 'Objects' },
  { emoji: '🔒', keywords: ['locked','security','private','lock'], category: 'Objects' },
  { emoji: '🔓', keywords: ['unlocked','open','access','lock'], category: 'Objects' },
  { emoji: '🔐', keywords: ['locked with key','secure','lock'], category: 'Objects' },
  { emoji: '🔨', keywords: ['hammer','tool','build','hit'], category: 'Objects' },
  { emoji: '⚒', keywords: ['hammer pick','tool','mining'], category: 'Objects' },
  { emoji: '🛠', keywords: ['tools','hammer wrench','repair','fix'], category: 'Objects' },
  { emoji: '🔧', keywords: ['wrench','tool','fix','repair'], category: 'Objects' },
  { emoji: '🔩', keywords: ['nut bolt','screw','fix','hardware'], category: 'Objects' },
  { emoji: '⚙', keywords: ['gear','settings','cog','mechanical'], category: 'Objects' },
  { emoji: '🪛', keywords: ['screwdriver','tool','fix'], category: 'Objects' },
  { emoji: '🔬', keywords: ['microscope','science','lab','biology'], category: 'Objects' },
  { emoji: '🔭', keywords: ['telescope','astronomy','star','space'], category: 'Objects' },
  { emoji: '🧪', keywords: ['test tube','lab','science','chemistry','experiment'], category: 'Objects' },
  { emoji: '🧬', keywords: ['dna','genetics','biology','science'], category: 'Objects' },
  { emoji: '💊', keywords: ['pill','medicine','drug','health'], category: 'Objects' },
  { emoji: '🩺', keywords: ['stethoscope','doctor','medical','health'], category: 'Objects' },
  { emoji: '💉', keywords: ['syringe','injection','vaccine','medical'], category: 'Objects' },
  { emoji: '🩹', keywords: ['bandage','band-aid','wound','heal'], category: 'Objects' },
  { emoji: '🧲', keywords: ['magnet','attract','pull'], category: 'Objects' },
  { emoji: '💣', keywords: ['bomb','explosion','dangerous'], category: 'Objects' },
  { emoji: '🪓', keywords: ['axe','chop','cut','wood'], category: 'Objects' },
  { emoji: '🔪', keywords: ['knife','cut','blade','kitchen'], category: 'Objects' },
  { emoji: '⚔', keywords: ['swords','crossed','fight','battle','medieval'], category: 'Objects' },
  { emoji: '🛡', keywords: ['shield','protect','defense','security'], category: 'Objects' },
  { emoji: '🪄', keywords: ['magic wand','magic','trick'], category: 'Objects' },
  { emoji: '🧸', keywords: ['teddy bear','stuffed animal','toy','soft'], category: 'Objects' },
  { emoji: '🪆', keywords: ['nesting dolls','matryoshka','russian'], category: 'Objects' },
  { emoji: '🎁', keywords: ['gift','present','birthday','surprise','wrap'], category: 'Objects' },
  { emoji: '🎀', keywords: ['ribbon','bow','gift','pink'], category: 'Objects' },
  { emoji: '🎊', keywords: ['confetti','party','celebrate'], category: 'Objects' },
  { emoji: '🎉', keywords: ['party','celebrate','popper','hooray'], category: 'Objects' },
  { emoji: '🪅', keywords: ['pinata','party','candy','celebrate'], category: 'Objects' },
  { emoji: '🎈', keywords: ['balloon','party','birthday','celebrate'], category: 'Objects' },
  { emoji: '🎆', keywords: ['fireworks','celebrate','new year'], category: 'Objects' },
  { emoji: '✨', keywords: ['sparkles','magic','shine','stars'], category: 'Objects' },
  { emoji: '🌟', keywords: ['glowing star','shine','bright','popular'], category: 'Objects' },
  { emoji: '⭐', keywords: ['star','rating','favorite'], category: 'Objects' },
  { emoji: '💫', keywords: ['dizzy star','spinning','wow'], category: 'Objects' },
  { emoji: '🔥', keywords: ['fire','hot','flame','burn','trending'], category: 'Objects' },
  { emoji: '💥', keywords: ['collision','boom','explosion','impact'], category: 'Objects' },
  { emoji: '❄', keywords: ['snowflake','cold','winter','freeze'], category: 'Objects' },
  { emoji: '💧', keywords: ['drop','water','rain','liquid'], category: 'Objects' },
  { emoji: '🌊', keywords: ['wave','ocean','sea','water','surf'], category: 'Objects' },
  { emoji: '🌈', keywords: ['rainbow','colorful','lgbtq','pride','sky'], category: 'Objects' },
  { emoji: '⚡', keywords: ['lightning','electric','bolt','thunder','energy','power'], category: 'Objects' },
  { emoji: '☀', keywords: ['sun','sunny','bright','warm','day'], category: 'Objects' },
  { emoji: '🌙', keywords: ['moon','night','crescent','luna'], category: 'Objects' },
  { emoji: '🌍', keywords: ['globe','earth','world','planet','africa','europe'], category: 'Objects' },
  { emoji: '🌎', keywords: ['globe','earth','world','planet','americas'], category: 'Objects' },
  { emoji: '🌏', keywords: ['globe','earth','world','planet','asia'], category: 'Objects' },
  // Work & Business
  { emoji: '📋', keywords: ['clipboard','list','notes','tasks'], category: 'Work' },
  { emoji: '📊', keywords: ['chart','graph','statistics','data','analytics'], category: 'Work' },
  { emoji: '📈', keywords: ['chart increasing','growth','trending up','stock'], category: 'Work' },
  { emoji: '📉', keywords: ['chart decreasing','decline','down','loss'], category: 'Work' },
  { emoji: '📌', keywords: ['pushpin','pin','location','note'], category: 'Work' },
  { emoji: '📍', keywords: ['pin','location','map','point'], category: 'Work' },
  { emoji: '📎', keywords: ['paperclip','attach','link'], category: 'Work' },
  { emoji: '📏', keywords: ['ruler','measure','straight'], category: 'Work' },
  { emoji: '📐', keywords: ['triangle ruler','angle','math','geometry'], category: 'Work' },
  { emoji: '✂', keywords: ['scissors','cut','craft'], category: 'Work' },
  { emoji: '🗂', keywords: ['card index dividers','organize','folder'], category: 'Work' },
  { emoji: '📁', keywords: ['folder','file','organize','directory'], category: 'Work' },
  { emoji: '📂', keywords: ['open folder','file','directory'], category: 'Work' },
  { emoji: '📄', keywords: ['page','document','file','paper'], category: 'Work' },
  { emoji: '📃', keywords: ['page with curl','document','paper'], category: 'Work' },
  { emoji: '📑', keywords: ['bookmark tabs','index','document'], category: 'Work' },
  { emoji: '📅', keywords: ['calendar','date','schedule','event'], category: 'Work' },
  { emoji: '📆', keywords: ['calendar','date','schedule'], category: 'Work' },
  { emoji: '🗒', keywords: ['notepad','notes','spiral'], category: 'Work' },
  { emoji: '📝', keywords: ['memo','note','write','edit','pencil'], category: 'Work' },
  { emoji: '✏', keywords: ['pencil','write','draw','edit'], category: 'Work' },
  { emoji: '✒', keywords: ['pen','write','sign'], category: 'Work' },
  { emoji: '🖊', keywords: ['pen','write','ballpoint'], category: 'Work' },
  { emoji: '🖋', keywords: ['fountain pen','write','ink'], category: 'Work' },
  { emoji: '💼', keywords: ['briefcase','business','work','job','office'], category: 'Work' },
  { emoji: '🎒', keywords: ['backpack','bag','school','travel'], category: 'Work' },
  { emoji: '🧳', keywords: ['luggage','suitcase','travel','bag'], category: 'Work' },
  { emoji: '🔍', keywords: ['search','magnify','zoom','find','look'], category: 'Work' },
  { emoji: '🔎', keywords: ['search','magnify','zoom','find'], category: 'Work' },
  { emoji: '📡', keywords: ['satellite dish','signal','broadcast'], category: 'Work' },
  { emoji: '🏫', keywords: ['school','education','building','study'], category: 'Work' },
  { emoji: '🎓', keywords: ['graduation','cap','education','diploma','degree'], category: 'Work' },
  { emoji: '📚', keywords: ['books','study','library','education','read'], category: 'Work' },
  { emoji: '📖', keywords: ['book','open','read','story'], category: 'Work' },
  { emoji: '📕', keywords: ['book','red','education'], category: 'Work' },
  { emoji: '📗', keywords: ['book','green'], category: 'Work' },
  { emoji: '📘', keywords: ['book','blue'], category: 'Work' },
  { emoji: '📙', keywords: ['book','orange'], category: 'Work' },
  { emoji: '📓', keywords: ['notebook','notes','study'], category: 'Work' },
  { emoji: '📔', keywords: ['notebook','decorative'], category: 'Work' },
  { emoji: '💰', keywords: ['money bag','cash','rich','wealth','dollar'], category: 'Work' },
  { emoji: '💵', keywords: ['dollar','money','cash','usd'], category: 'Work' },
  { emoji: '💳', keywords: ['credit card','payment','bank','card'], category: 'Work' },
  { emoji: '🏧', keywords: ['atm','cash machine','bank','money'], category: 'Work' },
  { emoji: '⚖', keywords: ['scales','justice','law','balance'], category: 'Work' },
  { emoji: '🔗', keywords: ['link','chain','connect','url'], category: 'Work' },
  // Nature & Weather
  { emoji: '🌸', keywords: ['cherry blossom','pink','flower','japan','spring'], category: 'Nature' },
  { emoji: '🌹', keywords: ['rose','red','flower','romance','love'], category: 'Nature' },
  { emoji: '🌻', keywords: ['sunflower','yellow','flower','summer'], category: 'Nature' },
  { emoji: '🌼', keywords: ['blossom','flower','yellow','spring'], category: 'Nature' },
  { emoji: '🌷', keywords: ['tulip','flower','spring','pink'], category: 'Nature' },
  { emoji: '🌱', keywords: ['seedling','plant','grow','green','nature'], category: 'Nature' },
  { emoji: '🌲', keywords: ['evergreen','pine','tree','forest','nature'], category: 'Nature' },
  { emoji: '🌳', keywords: ['deciduous','tree','nature','forest'], category: 'Nature' },
  { emoji: '🌴', keywords: ['palm tree','tropical','beach','summer'], category: 'Nature' },
  { emoji: '🌵', keywords: ['cactus','desert','dry','plant'], category: 'Nature' },
  { emoji: '🎋', keywords: ['tanabata tree','bamboo','japan'], category: 'Nature' },
  { emoji: '🍀', keywords: ['four leaf clover','luck','lucky','irish'], category: 'Nature' },
  { emoji: '☘', keywords: ['shamrock','clover','ireland','luck'], category: 'Nature' },
  { emoji: '🍁', keywords: ['maple leaf','autumn','fall','canada','red'], category: 'Nature' },
  { emoji: '🍂', keywords: ['fallen leaf','autumn','fall','brown'], category: 'Nature' },
  { emoji: '🍃', keywords: ['leaf','green','nature','wind'], category: 'Nature' },
  { emoji: '🌿', keywords: ['herb','plant','green','nature'], category: 'Nature' },
  { emoji: '🌾', keywords: ['wheat','grain','harvest','farm'], category: 'Nature' },
  { emoji: '🐚', keywords: ['shell','sea','beach','spiral'], category: 'Nature' },
  { emoji: '🌊', keywords: ['wave','ocean','sea','water'], category: 'Nature' },
  { emoji: '🌬', keywords: ['wind','blow','cold','breath'], category: 'Nature' },
  { emoji: '🌀', keywords: ['cyclone','hurricane','spiral','typhoon'], category: 'Nature' },
  { emoji: '🌈', keywords: ['rainbow','colorful','sky','rain'], category: 'Nature' },
  { emoji: '☀', keywords: ['sun','sunny','bright','warm','weather'], category: 'Nature' },
  { emoji: '🌤', keywords: ['partly cloudy','weather','sun','cloud'], category: 'Nature' },
  { emoji: '⛅', keywords: ['partly cloudy','weather','cloud','sun'], category: 'Nature' },
  { emoji: '🌧', keywords: ['rain','cloud','weather','rainy'], category: 'Nature' },
  { emoji: '⛈', keywords: ['storm','thunder','lightning','rain'], category: 'Nature' },
  { emoji: '🌩', keywords: ['lightning','storm','thunder'], category: 'Nature' },
  { emoji: '❄', keywords: ['snow','cold','winter','snowflake','freeze'], category: 'Nature' },
  { emoji: '☃', keywords: ['snowman','winter','cold','holiday'], category: 'Nature' },
  { emoji: '🌌', keywords: ['milky way','galaxy','space','stars','cosmos'], category: 'Nature' },
  { emoji: '🌠', keywords: ['shooting star','falling star','wish'], category: 'Nature' },
  { emoji: '🌅', keywords: ['sunrise','morning','dawn','sun'], category: 'Nature' },
  // Hearts & Symbols
  { emoji: '❤', keywords: ['red heart','love','romance','passion'], category: 'Symbols' },
  { emoji: '🧡', keywords: ['orange heart','love','care'], category: 'Symbols' },
  { emoji: '💛', keywords: ['yellow heart','love','happy'], category: 'Symbols' },
  { emoji: '💚', keywords: ['green heart','love','nature','health'], category: 'Symbols' },
  { emoji: '💙', keywords: ['blue heart','love','calm','sad'], category: 'Symbols' },
  { emoji: '💜', keywords: ['purple heart','love','military'], category: 'Symbols' },
  { emoji: '🖤', keywords: ['black heart','dark','goth'], category: 'Symbols' },
  { emoji: '🤍', keywords: ['white heart','love','pure'], category: 'Symbols' },
  { emoji: '💔', keywords: ['broken heart','sad','heartbreak'], category: 'Symbols' },
  { emoji: '💕', keywords: ['two hearts','love'], category: 'Symbols' },
  { emoji: '💞', keywords: ['revolving hearts','love'], category: 'Symbols' },
  { emoji: '💓', keywords: ['beating heart','love','life'], category: 'Symbols' },
  { emoji: '💗', keywords: ['growing heart','love'], category: 'Symbols' },
  { emoji: '💖', keywords: ['sparkling heart','love','shine'], category: 'Symbols' },
  { emoji: '💘', keywords: ['heart with arrow','love','cupid','crush'], category: 'Symbols' },
  { emoji: '💝', keywords: ['heart with ribbon','love','gift'], category: 'Symbols' },
  { emoji: '✅', keywords: ['check mark','done','complete','success','yes'], category: 'Symbols' },
  { emoji: '❌', keywords: ['cross mark','no','error','wrong','fail'], category: 'Symbols' },
  { emoji: '⭕', keywords: ['circle','ring','correct'], category: 'Symbols' },
  { emoji: '⚠', keywords: ['warning','caution','alert','danger'], category: 'Symbols' },
  { emoji: '🚫', keywords: ['prohibited','ban','no','forbidden','stop'], category: 'Symbols' },
  { emoji: '💯', keywords: ['hundred','perfect','score','100','complete'], category: 'Symbols' },
  { emoji: '❗', keywords: ['exclamation','alert','important'], category: 'Symbols' },
  { emoji: '❓', keywords: ['question','unknown','help'], category: 'Symbols' },
  { emoji: '🔴', keywords: ['red circle','dot'], category: 'Symbols' },
  { emoji: '🟠', keywords: ['orange circle','dot'], category: 'Symbols' },
  { emoji: '🟡', keywords: ['yellow circle','dot'], category: 'Symbols' },
  { emoji: '🟢', keywords: ['green circle','dot'], category: 'Symbols' },
  { emoji: '🔵', keywords: ['blue circle','dot'], category: 'Symbols' },
  { emoji: '🟣', keywords: ['purple circle','dot'], category: 'Symbols' },
  { emoji: '⚫', keywords: ['black circle','dot'], category: 'Symbols' },
  { emoji: '⚪', keywords: ['white circle','dot'], category: 'Symbols' },
  { emoji: '🏳', keywords: ['white flag','surrender'], category: 'Symbols' },
  { emoji: '🏴', keywords: ['black flag','pirate'], category: 'Symbols' },
  { emoji: '🔊', keywords: ['loud','volume','sound','speaker'], category: 'Symbols' },
  { emoji: '🔕', keywords: ['mute','silence','no sound'], category: 'Symbols' },
  { emoji: '🔔', keywords: ['bell','notification','alert','sound'], category: 'Symbols' },
  { emoji: '🔕', keywords: ['no bell','mute','silent'], category: 'Symbols' },
  { emoji: '📢', keywords: ['loudspeaker','announce','megaphone'], category: 'Symbols' },
  { emoji: '📣', keywords: ['megaphone','cheer','loud'], category: 'Symbols' },
  { emoji: '💬', keywords: ['speech bubble','message','chat','talk'], category: 'Symbols' },
  { emoji: '💭', keywords: ['thought bubble','think','wondering'], category: 'Symbols' },
  { emoji: '📧', keywords: ['email','envelope','message','mail'], category: 'Symbols' },
  { emoji: '📨', keywords: ['incoming envelope','message','mail'], category: 'Symbols' },
  { emoji: '📩', keywords: ['envelope arrow','mail','send'], category: 'Symbols' },
  { emoji: '📬', keywords: ['mailbox','letter','mail'], category: 'Symbols' },
  { emoji: '🔔', keywords: ['bell','alert','notification'], category: 'Symbols' },
  { emoji: '🔈', keywords: ['speaker','sound','volume'], category: 'Symbols' },
  { emoji: '🎵', keywords: ['music note','musical','song','tune'], category: 'Symbols' },
  { emoji: '🎶', keywords: ['music notes','musical','song','melody'], category: 'Symbols' },
  { emoji: '♻', keywords: ['recycle','green','eco','environment'], category: 'Symbols' },
  { emoji: '☮', keywords: ['peace','sign','hippie'], category: 'Symbols' },
  { emoji: '🆕', keywords: ['new','fresh','latest'], category: 'Symbols' },
  { emoji: '🆓', keywords: ['free','gratis'], category: 'Symbols' },
  { emoji: '🆒', keywords: ['cool'], category: 'Symbols' },
  { emoji: '🆗', keywords: ['ok','okay','yes'], category: 'Symbols' },
  { emoji: '🆘', keywords: ['sos','help','emergency','danger'], category: 'Symbols' },
  { emoji: '🔝', keywords: ['top','arrow','up'], category: 'Symbols' },
  { emoji: '🔛', keywords: ['on','arrow'], category: 'Symbols' },
  { emoji: '🔜', keywords: ['soon','arrow'], category: 'Symbols' },
  { emoji: '🔚', keywords: ['end','arrow'], category: 'Symbols' },
  { emoji: '🔙', keywords: ['back','arrow'], category: 'Symbols' },
  { emoji: '➡', keywords: ['right arrow','next','forward'], category: 'Symbols' },
  { emoji: '⬅', keywords: ['left arrow','back','previous'], category: 'Symbols' },
  { emoji: '⬆', keywords: ['up arrow','above'], category: 'Symbols' },
  { emoji: '⬇', keywords: ['down arrow','below'], category: 'Symbols' },
  { emoji: '↩', keywords: ['return','reply','back'], category: 'Symbols' },
  { emoji: '↪', keywords: ['forward','next'], category: 'Symbols' },
  { emoji: '🔀', keywords: ['shuffle','random','mix'], category: 'Symbols' },
  { emoji: '🔁', keywords: ['repeat','loop','cycle'], category: 'Symbols' },
  { emoji: '▶', keywords: ['play','start','begin'], category: 'Symbols' },
  { emoji: '⏸', keywords: ['pause','stop'], category: 'Symbols' },
  { emoji: '⏹', keywords: ['stop','square'], category: 'Symbols' },
  { emoji: '⏭', keywords: ['next track','skip','fast forward'], category: 'Symbols' },
  { emoji: '⏮', keywords: ['previous track','rewind','back'], category: 'Symbols' },
  { emoji: '⏩', keywords: ['fast forward','speed','quick'], category: 'Symbols' },
  { emoji: '⏪', keywords: ['rewind','back','fast'], category: 'Symbols' },
  { emoji: '⌛', keywords: ['hourglass','time','wait','loading'], category: 'Symbols' },
  { emoji: '⌚', keywords: ['watch','time','clock','wrist'], category: 'Symbols' },
  { emoji: '⏰', keywords: ['alarm clock','wake','time'], category: 'Symbols' },
  { emoji: '🕰', keywords: ['mantelpiece clock','time','vintage'], category: 'Symbols' },
  { emoji: '📍', keywords: ['pushpin','location','map'], category: 'Symbols' },
  // Flags
  { emoji: '🏁', keywords: ['checkered flag','race','finish','winner'], category: 'Symbols' },
  { emoji: '🚩', keywords: ['triangular flag','golf','danger','warning'], category: 'Symbols' },
  { emoji: '🎌', keywords: ['crossed flags','japan'], category: 'Symbols' },
];

export const EMOJI_CATEGORIES_ORDER = [
  'Smileys', 'People', 'Animals', 'Food', 'Travel',
  'Activities', 'Objects', 'Work', 'Nature', 'Symbols',
];

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return EMOJI_DATA.filter(
    (e) =>
      e.keywords.some((kw) => kw.includes(q)) ||
      e.category.toLowerCase().includes(q)
  );
}

export function getEmojisByCategory(): { label: string; emojis: EmojiEntry[] }[] {
  return EMOJI_CATEGORIES_ORDER.map((cat) => ({
    label: cat,
    emojis: EMOJI_DATA.filter((e) => e.category === cat),
  })).filter((c) => c.emojis.length > 0);
}
